import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-between font-roboto">
          {/* HEADER */}
          <div className="bg-neutral-300">
            <div className="mx-[220px] flex flex-row justify-between h-[270px] text-center content-center items-center">
              <Link href="/" className="text-neutral-700 text-[45px] font-roboto">ACB</Link>
              <div className="flex flex-row gap-7 text-center content-center items-center">
                {/* going to me a Map */}
              <Link href="/" className="text-neutral-700 font-light font-roboto">Home</Link>
              <Link href="/" className="text-neutral-700 font-light font-roboto">A Terapia</Link>
              <Link href="/" className="text-neutral-700 font-light font-roboto">Sobre mim</Link>
              <Link href="/" className="text-neutral-700 font-light font-roboto">A Clínica</Link>
              <Link href="/" className="text-neutral-700 font-light font-roboto">Blog</Link>
              </div>
              <div>
                <Link href="/candidatos" className="bg-gray-700 font-roboto font-light text-gray-200 px-6 py-2 rounded-xl">Contato</Link>
              </div>
            </div>
          </div>
           {/* HEADER */}
          <div className="">{children}</div>
        </div>
      </body>      
    </html>
  );
}
